Feature/object builder service
loyaltycorp/requesthandlers pull request #12
Opened 2019-07-24 03:55 UTC by merk

This is a POC PR to add an ObjectBuilder service to request handlers.

It provides a single point where valid request objects can be created, and is the first step towards validated objects for service consumption.

2019-07-25 23:15 UTC, edwardmurrell-loyaltycorp commented
Is this a proof of concept, or is the first pass, from which we will build further work on? If it's the former, we shouldn't merge it. If it's the latter, the points that need to be improved on need to be iterated for future work.

2019-07-26 01:29 UTC, edwardmurrell-loyaltycorp requested changes

2019-07-26 01:29 UTC, edwardmurrell-loyaltycorp commented on tests/Builder/ObjectBuilderTest.php
> +//    /**
Needs a comment on why this is commented out. Ideally mark as a skipped test with a link to the ticket to fux.

2019-07-26 01:29 UTC, edwardmurrell-loyaltycorp commented on tests/Builder/ObjectBuilderTest.php
> +     * Tests the build happy path.
Happy path is not descriptive enough.

2019-07-26 04:50 UTC, sjdaws approved these changes

2019-07-26 04:50 UTC, merged